# For internal use, but the requirements below
# describe the required dependencies
---
name: money

dev.edition: 2024
nix: true

up:
- packages:
  - libyaml
- ruby
- bundler
commands:
  test: bundle exec rake
