---
name: tzinfo
version: '2.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: d99fc1e536783b89a84df36a3ecf2d311fa17324
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
